### ISSUE TITLE
Double colon in line that starts with a space

### ISSUE THREAD

**Issue by voidzero** [enomsg/vim-haskellConcealPlus#3]
Hi,

Currently this line (№ 83) only turns `::` into `∷` if the line starts with a character.
`syntax match hs_DeclareFunction /^[a-z_(]\S*\(\s\|\n\)*::/me=e-2 nextgroup=hsNiceOperator contains=hs_FunctionName,hs_OpFunctionName`

Maybe you can use `^\s*` instead, because sometimes `::` can be found on a line that does start with a space.

**Comment by enomsg** [comment]
Sorry for the delay... I actually cannot reproduce the issue. :: gets concealed for me even if it starts with the space...

**Comment by NoAgendaIT** [comment]
Odd, I thought I already replied. Must have dreamed it. Anyway, I just checked this again, and am unable to reproduce my own issue.  So feel free to close it (I can't do that myself).  :grin:

**Comment by voidzero** [comment]
Derp. Maybe if I use the right account I can. :neckbeard:
