### ISSUE TITLE
Slow cursor

### ISSUE THREAD

**Issue by oblitum** [enomsg/vim-haskellConcealPlus#6]
Moving after having it enabled is quite slower than normal. This doesn't happen with Twinside/vim-haskellConceal.

**Comment by oblitum** [comment]
Entering text is even slower.

**Comment by enomsg** [comment]
I use pretty modest laptop (AMD E-350 based), and it works quite fast for me (read I don't feel any difference with or without concealing). Can you provide your vimrc?
Thanks!

**Comment by oblitum** [comment]
This is my current local .vimrc: https://gist.github.com/oblitum/b5c1a4a30d34a1833144
base on the one at my dotfiles https://github.com/oblitum/dotfiles/blob/osx/.vimrc.

It's big, full of plugins, so I guess it may be hard to spot anything, but I've tried haskellCancelPlus in isolation and got the same slowness. So I had to use the older conceal plugin =/

**Comment by oblitum** [comment]
Ah, I'm sorry, my bad. In isolation it's not slow! But it's... when coupled with something else. I must find what makes it so slow.

**Comment by oblitum** [comment]
Also, taking the opportunity I'm looking into this. It seems to not play well with raichoo/haskell-vim. When enabling it I miss the conceal for `where`...

**Comment by oblitum** [comment]
ah, another one that mess with `where`, and the cause of the slowness when coupled with haskellConcealPlus is [dag/vim2hs](https://github.com/dag/vim2hs).

I think I may have too many haskell plugins trying to do the same thing at once.

**Comment by oblitum** [comment]
Sadly, haskell-vim provide such nice highlighting... I'd like haskellConcealPlus could play nice with colorschemes, not sure it's possible.

**Comment by oblitum** [comment]
It seems vim2hs is already slow enought by itself, it gets worse coupled with haskellConcealPlus.

**Comment by oblitum** [comment]
I'm left with raichoo and haskellConcealPlus. Removed vim2hs. Now looking for a why to have concealing working fully even with raichoo/haskell-vim.

**Comment by oblitum** [comment]
Removing the line from haskell-vim that sets `where` as keyword solved it for me although I now miss highlighting for the keyword when expanded from conceal. Do you have any tip regarding these incompatibilites?

**Comment by enomsg** [comment]
I'm glad you found the cause.

> I think I may have too many haskell plugins trying to do the same thing at once.

I have the same exact impression. I find that vim, in general, is hard to keep in manageable state with a lot of plugins. I am not sure if it is cultural ("plugins tend to do too many things at once") or architectural ("plugins allowed to do too many things at once") flaw of vim plugins, but adding another plugin to my vim setup definitely breaks one or another thing, all the time.

More isolated, "functional" editor would be nice to have. Maybe it is Yi, I only briefly looked into it... I'm dreaming of adding concealing support to Yi one day, and switching to it.

Regarding haskell-vim, unfortunately I don't use it, so I don't know.

**Comment by oblitum** [comment]
Ok. For me, it's hard to think to move out from Vim/Neovim, I'm too addict.

**Comment by oblitum** [comment]
I suspect I'll try haskellConcealPlus for a while, but it's a far reaching idea to really on, so I suspect I may end up getting back to fixed-width text sooner or later.
